# load-csv-into-rdb
SanjayKAroraPhD@gmail.com <br>
February 2019

## Description
Load a csv into a pandas dataframe and persist to a mysql db

In [24]:
import pandas as pd
import csv 
from pandas.io import sql
from sqlalchemy import create_engine
from sqlalchemy import types

In [25]:
PATENT_DATA = '/Users/sanjay/dev/EAGER/data/patents/'
ENGINE = create_engine('mysql://root:innovate@localhost/patent_20170808?charset=utf8', encoding='utf-8')
CON = ENGINE.connect()

In [26]:
table_name = 'eager_assignee'
file = PATENT_DATA + table_name + '.csv'
print (file)
table_df = pd.read_csv(file, sep=',', encoding='utf-8', warn_bad_lines=True, error_bad_lines=False)
table_df.head()

/Users/sanjay/dev/EAGER/data/patents/eager_assignee.csv

,firm,lookup_firm,firm_length,name_clnd,name_length,manual_fix,hit_url,hit_url_length,rank,matches,public,acquired_merged,Votes,Group,nano,green,synbio,count_all_ind,max_emps,size_state
0,22nd Century Limited,22nd Century Limited,20.0,"22nd Century Group, Inc. - Official Site",40,NaN,xxiicentury.com/,27,1,2,0,0,5,0,0,0,1,1,734,FirmSize.LARGE_FIRM
1,3M Innovative Properties Company,3M Innovative Properties Company,32.0,3M - Official Site,18,NaN,3m.com/,19,2,1,0,0,3,1,1,1,1,3,60593,FirmSize.LARGE_FIRM
2,540 Grid Solutions,540 Grid Solutions,18.0,540 Grid Solutions LLC Company Profile | Key C...,57,1.0,NaN,106,1,3,0,0,0,2,0,1,0,1,18,FirmSize.SMALL_FIRM
3,646840 Alberta Ltd.,646840 Alberta,14.0,"16440 S Alberta Ct, Homer Glen, IL 60491 - rea...",54,1.0,NaN,99,1,1,0,0,0,3,0,1,0,1,0,FirmSize.UNDEFINED
4,AAC Technologies Pte. Ltd.,AAC Technologies Pte,20.0,AAC Technologies Pte. Ltd.: Private Company In...,59,1.0,NaN,82,1,3,0,0,0,4,1,0,0,1,2174,FirmSize.LARGE_FIRM

In [13]:
max(table_df['firm'].apply(len))

TypeError: object of type 'float' has no len()

In [27]:
table_df.to_sql(name=table_name,con=CON,if_exists='replace', index=False, 
                dtype={'lookup_firm': types.NVARCHAR(length=256)}
               )

In [15]:
CON.close()